resources:
- name: openbank_apis
  type: solutions.api
  properties:
    inputs:
    - name: org
      prompt: Edge Org name
    - name: username
      prompt: Username
      ifNotPresent: token
    - name: password
      prompt: Password
      hidden: true
      ifNotPresent: token
    - name: env
      prompt: Edge Org Environment
    - name: usergrid_org
      prompt: BaaS Org name
    - name: usergrid_app
      prompt: BaaS App name
    - name: usergrid_client_id
      prompt: BaaS Org Client Id
    - name: usergrid_secret
      prompt: BaaS Org Client Secret
    - name: consentSessionKey
      prompt: Enter Consent Session Key
    - name: jwtSignKey
      prompt: Enter Login App Key
    - name: BankPrivateKey
      prompt: Enter Bank's Private Key
    - name: TppPublicKey
      prompt: Enter Tpp's Public Key
    
    configurations:
    - env: test
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      sms_endpoint: https://rest.nexmo.com/sms/json

    - env : prod
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      sms_endpoint: https://rest.nexmo.com/sms/json

    edgeOrg:
    script: gulpfile.js
    basePath: .
    subResources:
    - name: baas_data_load
      type: baasLoadData
      items:
      - name: accounts
        file: setup/data/accounts.json
      - name: accountsrequests
        file: setup/data/accountsrequests.json
      - name: payments
      - name: payment-submissions
      - name: beneficiaries
        file: setup/data/beneficiaries.json
      - name: customers
        file: setup/data/customers.json
      - name: directdebits
        file: setup/data/directdebits.json
      - name: standingorders
        file: setup/data/standingorders.json
      - name: transactions
        file: setup/data/transactions.json
      - name: products
        file: setup/data/products.json
      - name: id-tokens
      - name: users
        file: setup/data/users.json
      - name: consents
        file: setup/data/consents.json
      - name: locations
        file: setup/data/locations.json
      - name: bankproducts
        file: setup/data/bankproducts.json
    - name: cacheResources
      type: cache
      items:
      - name: sms-token-cache
        payload: '{ "name": "sms-token-cache"}'
      - name: nonce-cache
        payload: '{ "name": "nonce-cache"}'
    - name: message_kvm
      type: kvm
      items:
      - name: BankKVM
        payload: '{ "name" : "BankKVM", "entry" : [ { "name" : "privateKey", "value" : "{{ BankPrivateKey }}" } ] , "encrypted": "true"}'
    
    - name: replaceorgvalues
      type: configSubstitutions
      items:
      - name: baasBasePath
        filePaths: ['src/gateway/user-management/target/apiproxy/targets/default.xml','src/gateway/customer-management/target/apiproxy/targets/default.xml','src/gateway/accounts-connector/target/apiproxy/policies/Assign-Target-URL.xml','src/gateway/locations-connector/target/apiproxy/policies/Assign-Target-URL.xml','src/gateway/products-connector/target/apiproxy/policies/Assign-Target-URL.xml']
        value: '{{ baas_host }}/{{ usergrid_org }}/{{ usergrid_app }}'
      - name: baasURI
        filePaths: ['src/gateway/consent-management/target/apiproxy/resources/node/package.json','src/gateway/payments-connector/target/apiproxy/resources/node/package.json']
        value: '{{ baas_host }}'
      - name: baasOrg
        filePaths: ['src/gateway/consent-management/target/apiproxy/resources/node/package.json','src/gateway/payments-connector/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_org }}'
      - name: baasApp
        filePaths: ['src/gateway/consent-management/target/apiproxy/resources/node/package.json','src/gateway/payments-connector/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_app }}'
      - name: baasClientId
        filePaths: ['src/gateway/accounts-connector/target/apiproxy/resources/node/package.json','src/gateway/consent-management/target/apiproxy/resources/node/package.json','src/gateway/payments-connector/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_client_id }}'
      - name: baasClientSecret
        filePaths: ['src/gateway/accounts-connector/target/apiproxy/resources/node/package.json','src/gateway/consent-management/target/apiproxy/resources/node/package.json','src/gateway/payments-connector/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_secret }}'
      - name: edgeBasePath
        filePaths: ['src/gateway/login-app/target/apiproxy/resources/node/config.json']
        value: 'https://{{ org }}-{{ env }}.apigee.net'
      - name: sms_endpoint
        filePaths: ['src/gateway/sms-token/target/apiproxy/targets/confirmation.xml','src/gateway/sms-token/target/apiproxy/targets/default.xml']
        value: '{{ sms_endpoint }}'
      - name: jwtSignKey
        filePaths: ['src/gateway/login-app/target/apiproxy/resources/node/config.json']
        value: '{{ jwtSignKey }}'
      
    - name: bank_apis
      type: proxy
      items:
      - name: accounts-connector
        apiName: AccountsOBv1.0Connector
      - name: sms-token
        apiName: SmsTokenOBv1.0
      - name: consent-management
        apiName: ConsentManagementOBv1.0
      - name: user-management
        apiName: UserManagementOBv1.0
      - name: customer-management
        apiName: CustomerManagementOBv1.0
      - name: login-app
        apiName: LoginAppOBv1.0
      - name: payments-connector
        apiName: PaymentsOBv1.0Connector
      - name: locations-connector
        apiName: locations-connector
      - name: products-connector
        apiName: products-connector
    - name: developers
      type: developer
      items:
      - payload: '{"email":"openbank@apigee.net", "firstName":"OpenBank","lastName":"Developer","userName":"openbank"}'
        email: openbank@apigee.net
    - name: apiProducts
      type: product
      items:
      - payload: '{"approvalType":"auto", "attributes":[{"name":"access","value":"private"}], "displayName":"Internal Consent APIs","name":"internal_apis","environments":["test","prod"],"scopes":[]}'
        name: internal_apis
    - name: developerApps
      type: app
      items:
      - name: internal_app
        payload: '{"name":"internal_app","callback":"http://localhost/","email":"openbank@apigee.net","apiProducts":"internal_apis"}'
        assignResponse:
        - from: credentials.0.consumerKey
          to: apiKey_IA
    - name: replace_consent_app_key
      type: configSubstitutions
      items:
      - name: internalAppKey
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json','src/gateway/accounts/target/apiproxy/policies/Assign-APIKey-Header.xml','src/gateway/accounts/target/apiproxy/policies/Fetch-Account-Consent.xml','src/gateway/accounts/target/apiproxy/policies/Get-Acc-Req-Data.xml','src/gateway/accounts/target/apiproxy/policies/Update-Access-Count.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Update-Account-Request.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Update-Payment-Request.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Validate-Account-Request.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Validate-Payment-Request.xml','src/gateway/payments/target/apiproxy/policies/Assign-APIKey-Header.xml','src/gateway/payments/target/apiproxy/policies/Service-Callout-Validate-Payment-Request-Status.xml','src/gateway/payments/target/apiproxy/policies/Service-Callout-Fetch-and-Validate-Consent.xml']
        value: '{{ apiKey_IA }}'
      - name: edgeBasePath
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json','src/gateway/accounts/target/apiproxy/policies/Fetch-Account-Consent.xml','src/gateway/accounts/target/apiproxy/policies/Get-Acc-Req-Data.xml','src/gateway/accounts/target/apiproxy/policies/Update-Access-Count.xml','src/gateway/accounts/target/apiproxy/targets/default.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Update-Account-Request.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Update-Payment-Request.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Validate-Account-Request.xml','src/gateway/oauth/target/apiproxy/policies/Service-Callout-Validate-Payment-Request.xml','src/gateway/oauth/target/apiproxy/targets/default.xml','src/gateway/payments/target/apiproxy/policies/Service-Callout-Validate-Payment-Request-Status.xml','src/gateway/payments/target/apiproxy/policies/Service-Callout-Fetch-and-Validate-Consent.xml','src/gateway/payments/target/apiproxy/targets/default.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net'
      - name: consentSessionKey
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json']
        value: '{{ consentSessionKey }}'
      - name: jwtSignKey
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json']
        value: '{{ jwtSignKey }}'
      - name: baasBasePath
        filePaths: ['src/gateway/oauth/target/apiproxy/policies/Service-Callout-Create-ID-token.xml']
        value: '{{ baas_host }}/{{ usergrid_org }}/{{ usergrid_app }}'
    - name: deploy_remaining_apis
      type: proxy
      items:
      - name: oauth
        apiName: OauthOBv1.0
      - name: consent-app
        apiName: ConsentAppOBv1.0
      - name: accounts
        apiName: AccountsOBv1.0
      - name: payments
        apiName: PaymentsOBv1.0
      - name: locations
        apiName: locations
      - name: products
        apiName: products
    - name: remainingApiProducts
      type: product
      items:
      - payload: '{"approvalType":"auto", "displayName":"Account APIs","name":"account_apis","environments":["test","prod"],"scopes":["accounts","openid"], "proxies":["oauth", "accounts"]}'
        name: account_apis
      - payload: '{"approvalType":"auto", "displayName":"Payments APIs","name":"payment_apis","environments":["test","prod"],"scopes":["payments","openid"], "proxies":["oauth", "payments"]}'
        name: payment_apis
    - name: remainingDeveloperApps
      type: app
      items:
      - name: AISP_App
        payload: '{"name":"AISP_App","attributes":[{"name":"tppId","value":"12345"},{"name":"publicKey","value":"{{ TppPublicKey }}"}],"callback":"http://localhost/,https://api.enterprise.apigee.com/v1/o/{{ org }}/apimodels/accounts-apis-v1-0/templateauths/PSUOAuth2Security/callback","email":"openbank@apigee.net","apiProducts":"account_apis"}'
        assignResponse:
        - from: credentials.0.consumerKey
          to: apiKey_AISP
        - from: credentials.0.consumerSecret
          to: apiSecret_AISP
        - from: appId
          to: appId_AISP
      - name: PISP_App
        payload: '{"name":"PISP_App","attributes":[{"name":"tppId","value":"12345"},{"name":"publicKey","value":"{{ TppPublicKey }}"}],"callback":"http://localhost/,https://api.enterprise.apigee.com/v1/o/{{ org }}/apimodels/payments-apis-v1-0/templateauths/PSUOAuth2Security/callback","email":"openbank@apigee.net","apiProducts":"payment_apis"}'
        assignResponse:
        - from: credentials.0.consumerKey
          to: apiKey_PISP
        - from: credentials.0.consumerSecret
          to: apiSecret_PISP
        - from: appId
          to: appId_PISP
    - name: copyConfigTemplate
      type: util
      items: 
      - action: copy
        from: test/config.orig
        to: test/config.json

    - name: replace_test_keys
      type: configSubstitutions
      items:
      - name: keyAISP
        filePaths: ['test/config.json']
        value: '{{ apiKey_AISP }}'
      - name: keyPISP
        filePaths: ['test/config.json']
        value: '{{ apiKey_PISP }}'
      - name: edgeBasePath
        filePaths: ['test/config.json']
        value: '{{ org }}-{{ env }}.apigee.net'
      - name: internalAppKey
        filePaths: ['test/config.json']
        value: '{{ apiKey_IA }}'
    
